# Usa imagem leve com Python
FROM python:3.10-slim

# Define diretório de trabalho dentro do container
WORKDIR /app

# Copia todos os arquivos do projeto
COPY . .

# Instala utilitários e dependências de compilação necessárias
RUN apt-get update && \
    apt-get install -y wget gcc g++ cmake && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir gdown && \
    apt-get remove -y gcc g++ cmake && \
    apt-get autoremove -y && \
    apt-get clean

# Cria diretório e baixa modelo Phi-2 do Google Drive
RUN mkdir -p modelo && \
    gdown https://drive.google.com/uc?id=1lhxoUMyKeOkpvchbjihIGTCEbV3x_Bt9 -O modelo/phi2.gguf

# Expondo porta da API
EXPOSE 8000

# Inicia a API FastAPI com Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
